package constants

const (
	CHARSET_UTF8               = "utf-8"
	DATETIME_FORMAT            = "2006-01-02 15:04:05"
	TIMESTAMP_FORMAT           = "2006-01-02 15:04:05"
	SIGN_METHOD_MD5            = "md5"
	SIGN_METHOD_HMAC           = "hmac"
	SIGN_METHOD_HMAC_SHA256    = "hmac-sha256"
	LOG_FILE_NAME              = "topclient.log"
	ACCEPT_ENCODING            = "Accept-Encoding"
	CONTENT_ENCODING           = "Content-Encoding"
	CONTENT_ENCODING_GZIP      = "gzip"
	ERROR_RESPONSE             = "error_response"
	ERROR_CODE                 = "code"
	ERROR_MSG                  = "msg"
	QIMEN_CLOUD_ERROR_RESPONSE = "response"
	QIMEN_CLOUD_ERROR_CODE     = "code"
	QIMEN_CLOUD_ERROR_MSG      = "message"
	SDK_VERSION                = "top-sdk-go-20191214"
	APP_KEY                    = "app_key"
	FORMAT                     = "format"
	METHOD                     = "method"
	TIMESTAMP                  = "timestamp"
	VERSION                    = "v"
	SIGN                       = "sign"
	SIGN_METHOD                = "sign_method"
	PARTNER_ID                 = "partner_id"
	SESSION                    = "session"
	FORMAT_XML                 = "xml"
	FORMAT_JSON                = "json"
	SIMPLIFY                   = "simplify"
	TARGET_APP_KEY             = "target_app_key"
	QM_ROOT_TAG_REQ            = "request"
	QM_ROOT_TAG_REP            = "response"
	QM_CUSTOMER_ID             = "customerId"
	QM_CONTENT_TYPE            = "text/xml;charset=utf-8"
	QM_TARGETAPPKEY            = "targetAppKey"
	CTYPE_DEFAULT              = "application/octet-stream"
	CTYPE_FORM_DATA            = "application/x-www-form-urlencoded"
	CTYPE_FILE_UPLOAD          = "multipart/form-data"
	CTYPE_TEXT_XML             = "text/xml"
	CTYPE_TEXT_PLAIN           = "text/plain"
	CTYPE_APP_JSON             = "application/json"
	READ_BUFFER_SIZE           = 1024 * 4
)
